### ISSUE TITLE
Horus port

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#3159]
**Port from master branch:**
- [x] S.PORT Powerbox support (pull #3166) + adaptation to Horus GUI 
- [x] Crossfire (pull #3165) + adaptation to Horus GUI 
- [x] LR12 EU compatibility (done in e8983250ca3f288ca8ec8adaa744ee813fcebdbe) + adaptation to Horus GUI 

**Can be done before we have the full radio in hands:**
- [ ] Implement the CurvesAll screen designed by Martin
- [ ] Model Selection: add the possibility to move models and categories in the list
- [x] Add the support for jpg and/or png (issue #3167)
- [ ] Lua: export all LCD functions to the interpreter
- [ ] Lua: design a test / demo screen to show the possibilities
- [ ] Add a way to override all default main views by custom ones, Lua based

**Can be done after we have the full radio in hands:**
- [ ] ON and OFF sequences
- [x] Analogs and switches
- [ ] Pulses: PPM (done in #3341) / DSM2 / PXX / Crossfire
- [ ] FrSky D / S.PORT telemetry
- [x] RTC
- [ ] Watch Dog Timer reboot (prepared in #3341)
- [x] Radio stays powered on after reboot (done in #3341)

**Companion**
- [ ] Think to a way to show the models list, a tree?
- [ ] SD models structure export / import

**Comment by hrenz** [comment]
Hy Bertrand
Can be done before we have the full radio in hands:
Language specific characters at companion and simulator
Screens size reduction  to max 1000x750 pixel for normal 15'' Notebooks at simulator
At Log switches the infos for the Inputs: Funktion, V1, V2 AND  .....
Beep Pitch at radios setup at Companion, now only at TX
Spezial funktions Inc / Dec not only +/-1   frees settings +/-1  .....   +/-10 ..... +/-25

**Comment by kilrah** [comment]
These are all existing issues and none of them are directly related to or needed for the Horus. I.e. nothing to do in here.

**Comment by projectkk2glider** [comment]
One down :smile: , many to go...

**Comment by bsongis** [comment]
Yes but in fact no, the adaptation to the Horus GUI is needed
