### ISSUE TITLE
GVARS redesign

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#3185]
As stated by many issues. GVars would benefit from 3 more parameters:
- [x] Add an unit. It would solve our problem with GVars used for channels. Some like to use 512us, other 100%, other 1024(raw)
- [x] Add a prec. It would take care of #1361 and #905
- [x] Add a min/max which would be used by the AdjustGVar function
- [x] AdjustGVar (+/-X) instead of AdjustGVar(+/-1), people wait for this function since long, cf #1713 

GVars are needed in some more menus:
- [ ] Audio Volume #2248
- [ ] Slow / Delay

There is also some existing bugs related to gvars when using FUNC_ADJUST_GVAR: 
- [x] The increment/decrement is missing a limit check. The value of gvar can thus be incremented or decremented beyond the normal range. (#2917)
- [x] Another AdjustGVar issue #3103

**Comment by bsongis** [comment]
GVars are needed in some more menus:
[ ] Audio Volume #2248
[ ] Slow / Delay

**Comment by hrenz** [comment]
Hy Bertrand,
would be very nice!
Thanks!!

**Comment by arronbates** [comment]
very cool

**Comment by projectkk2glider** [comment]
There is also one existing subtle bug related to gvars when using FUNC_ADJUST_GVAR: 
* the increment/decrement is missing a limit check. The value of gvar can thus be incremented or decremented beyond the normal range.

**Comment by kilrah** [comment]
That was also an issue I think, someone wanted to be able to set a limit to adjustment range. Will see if I can find it.

**Comment by hrenz** [comment]
Hy,
I think about GVAR 
Min, Max, Start value, Ind/Dec Steps, Typ % or us

**Comment by fraternl** [comment]
@bsongis 
I haven't been following developments in the last 2 months and noticed these changes in gvar.
From what I gather I can soon change a gvar using a stick as a direct source and let it change a gvar within my desired range.
This means that one doesn't have to use a helper channel with a dedicated curve to achieve this (unless I want even more control).
Am I correct in this?

http://www.rcgroups.com/forums/showpost.php?p=33597465&postcount=2349

**Comment by kilrah** [comment]
No, the idea would have been to use the new limits as a clamp, not scaled to the input.

Reason is that if we scaled and that's not what the user wants it's hard to "undo" the scaling, while the current way of using a channel makes the opposite easy.

**Comment by kilrah** [comment]
Another GVAR issue: #3103

**Comment by bsongis** [comment]
https://files.gitter.im/opentx/opentx/MRgv/Sn_mek-obrazovky-po__zen_-2016-01-03-21_03_43.png

**Comment by bsongis** [comment]
Some progress on this in my last commit. GVars names are now reduced to 3 chars. Curves as well. Names for GVars and Curves will be used everywhere in the firmware now.

Tests needed please!

**Comment by lshems** [comment]
any suggestions for tests?
Able to do some.

**Comment by hmichl** [comment]
I really like this thread and support the idea of having GVARs at additional places. One request I would like to add is having also the possibility to have a GVAR instead of a value at the weight of trainer-functions. I want to be able to change this weight dependend on the position of the stick of the master-transmitter (for example the more I move my stick to a maximum position the less weight the student has). I already implmemented this functionality with a lot of mixers using TR1 to TR4, but having it where it belongs to (in my opinion :-) would be great!

In addition to this, it would generally be cool to have the choice of either GVARs or the value of a channel. I often use channels and functions to generate values, but then have to assign exactly these values to a GVAR. Would be cool to skip this one step.

**Comment by RCdiy** [comment]
I've defined LS1-5 like this. Ignore L1.
![56ls](https://user-images.githubusercontent.com/20209851/35884191-db80ce42-0b57-11e8-9977-98472e052909.png)
GV1 changes with stick THR
GV2 is 50%
GV3 is 50
When comparing THR against GV2 and GV3 should the behaviour not be different?
When THR is equal to 5 why is it equal to both 50% and 50?
I thought THR had unit % so 5 should not be equal to 50%.
![5](https://user-images.githubusercontent.com/20209851/35884443-ad61eac2-0b58-11e8-966e-93568658b451.png)
![6](https://user-images.githubusercontent.com/20209851/35884444-ad6db9ba-0b58-11e8-86ef-4c5d9e6280b2.png)

Here is the OTX file. Rename and remove .txt to use it.
[GVARtests.otx.txt](https://github.com/opentx/opentx/files/1700805/GVARtests.otx.txt)

**Comment by kilrah** [comment]
Ah I believe the % is only for display, you need to set the "precision" for actual scaling.
