### ISSUE TITLE
Companion 2.2 problems

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4224]
Priority issues:
- [x]  Simulate radio from within companion with Horus selected still overwrites everything in the configured SD card directory instead of using a temp folder

- [x] Horus: Switch warnings read wrong (Aup Boff Cmid Dup Eup Fdown Gup on radio gives all on, A mid, G mid, rest up in companion)

- [x] Model Settings / Horus: Module settings not read correctly

- [x] Flight modes / Horus: Trim values not read

- [x] Horus / Source list: Shift of 4 elements (SC read as SG, MAX read as CYC2, TR4 read as TR8

- [x] Horus / Switch list: Shift of 22 elements somewhere (L2 read as L24, FM1 read as ---)

- [x] All Radios / Flight modes: Trim "OFF" missing in dropdown

- [x] Simulate single Horus model causes crash on some models, need to retest once other issues are fixed

- [x] X7: Completely broken for me, stray chars in model list names, no inputs/mixes/garbage in outputs/heli

- [x] Horus: Old fourcc needs to be recognised and automatically updated

- [x] When reading from Horus the file->save command saves straight to the radio instead of creating an OTX file (same problem when opening eeprom from another radio and converting to Horus, we're still wotking on the original file instead of moving to otx)

- [x] Saving the results of a something->Horus conversion (using save as due to above problem) and reopening the default "Models" category now has an empty name. When simulating this straight away there is an "invalid model" in first position, and the selected model is not the one highlighted in the companion model list. Model select page in the simulator shows no selected model

- [x] Load an X9E EEPROM, convert to Horus, launch simulator, everything's empty

- [x] X7 export corrupts input names and telemetry sensors (also custom scripts and modules after further investigation)

- [x] X7 limits divided by 10 (setting 50% results in 95% travel)

- [x] X7 switch /pot names corrupted on import

General issues:

- [x] Selected model not showing / can't be changed

- [x] Radio settings / Horus: Haptic settings should be enabled, haptic length missing

- [x] Model settings / Horus: Antenna selection for internal module missing

- [x] Model settings / Horus: Trainer settings missing

- [x] Telemetry / Horus: Protocol selection enabled when it shouldn't

- [x] RSSI alarms have the Orange/red dropdowns instead of low/critical

- [x] Top bar settings should be hidden

- [x] Telemetry screens should be hidden

- [x] X7 simulator not really usable (switches/pots, no telemetry simulator etc)

- [x] Horus import: Haptic "All" read as "No Keys"

- [x] X7: External module Multi/Bayang/Bayang comes as prot empty, subprot DEFAULT

- [x] Flashing Horus firmware we get a "maybe not a valid firmware file" message box

- [x] X7/Model settings/Hardware: Shows SA-SF labels instead of SA-SD SG-SH

- [x] Horus models cannot be moved from one category to another

- [x] Horus model list: cannot paste model into category (only on existing model). #4371

- [x] Horus model list: drag&drop of models between two model list does not work.

- [x] ~~Horus model list: can't rename category~~

- [x] Horus: Missing T5/T6/Joystick in source lists

- [x] Horus: Missing default inputs/mixes in new model

- [x] Horus: Internal/external antenna choice showing up even if internal module is OFF (should be in modulePanel too)

- [x] Simulate, print, cut/copy/paste icons only become enabled after finding a way to make the mdichild lose and regain focus, and then only sometimes. 

- [x] New Horus document could create a default catrgory and model

- [x] Horus: Jpg model images not showing on non-dev machines (guess we DO need those qt image plugins packaged after all)
- [x] Warning on EEPROM upgrade missing
- [X] Models with an empty name converted to Horus should have their default name set

Minor:

- [x] Radio settings: Hardware->Serial port, ADC filter, BT missing

- [x] Radio settings / Horus Backlight off brightness missing, Adjsut RTC missing

- [x] Model setup / Horus: Image missing

- [x] Drag and drop a .otx doesn't work to open it

- [x] Compare Models not working (dragging from the new treeview doesn't work) #4620

- [x] Multi missing option value setting (fixed by #4459)

- [X] Allow eepe files only for opening, not for saving

- [x] `Show Splash Screen on Startup` option in general settings should be removed 7d849e1c4c65de064c563862f0253944d98dc22a

**Comment by kilrah** [comment]
No problem to report for Taranis except for the selected model thing

**Comment by benoit35690** [comment]
I have added a separate issue 4225 dealing with the multiprotocol (2 issues actually)

**Comment by projectkk2glider** [comment]
I will start on the first item *Simulate radio from within companion with Horus selected still overwrites everything in the configured SD card directory instead of using a temp folder*

**Comment by mhotar** [comment]
There is nothing for me in your list?
![simufrontq7 svg](https://cloud.githubusercontent.com/assets/6114100/21946387/8c6c3872-d9e0-11e6-82c2-4ed5c5860ef3.png)

**Comment by kilrah** [comment]
Awesome!

**Comment by bsongis** [comment]
wow, it's really nice!

**Comment by mhotar** [comment]
Thank you :)

**Comment by 3djc** [comment]
U Rule!

**Comment by mpaperno** [comment]
Very nice!  :)    I'm going to work on the simulator UI so that we don't have do duplicate the whole form for the 5th time (would that be "quintuplicating?").

I'm having some trouble with the list identifying which part(s) is/are affected, or where to look... companion vs. simulator (and maybe simu or firmware also?).  I realize this was a quick list mostly for people who already know what it all means.  But any further clues may help :)

**Comment by projectkk2glider** [comment]
I will take `Drag and drop a .otx doesn't work to open it`

**Comment by 3djc** [comment]
Added : Horus models cannot be moved from one category to another

**Comment by projectkk2glider** [comment]
Added: `Show Splash Screen on Startup` option in general settings should be removed

**Comment by projectkk2glider** [comment]
Added:
 -  Horus model list: cannot paste model into category (only on existing model).
 -  Horus model list: drag&drop of models between two model list does not work.

**Comment by kilrah** [comment]
Some updates

**Comment by projectkk2glider** [comment]
Added:  Horus model list: can't rename category (from #4339)

**Comment by kposadowsky** [comment]
Tmp1 and Tmp2 are not simulated from csv.

**Comment by kilrah** [comment]
Off topic. Only what's in the window is simulated.

**Comment by Riffer** [comment]
Maybe I misunderstand this video where I see Tmp1 and Tmp2 values in the simulation are being played from the csv:

https://www.youtube.com/watch?v=mYgJ-Vn1h9M

**Comment by kilrah** [comment]
Ah yes they are indeed. You must make sure the IDs are the same than what's configured in the model's telemetry. Again waaay off topic.

**Comment by projectkk2glider** [comment]
Keeping so many issues in this one is getting a bit hard to track. For example it is difficult to easily see which sub issues were fixed in which release. I propose we don't add any more new issues here.

**Comment by kellybyrd** [comment]
I was about to add something here,  the "duplicate" context menu option doesn't do anything. The function isn't defined in MdiChild. I'm working on it now let me know if it should be part of this or a new issue.

**Comment by mpaperno** [comment]
Last item in list is done (drag/drop).  Woot!  Close?

**Comment by bsongis** [comment]
Thanks for your help on the last open items!

**Comment by kilrah** [comment]
👍
